/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.Gestion_contraseñas;
import Controlador.Gestion_postulante;
import Controlador.Gestion_emails;
import Controlador.Procesar_opciones;
import Controlador.Requerimineto;
import Modelo.obtener_identifi;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

/**
 *
 * @author COSAS DE LA Y
 */
public class Meritos extends javax.swing.JFrame {

    String nombre_postulante;
    String bachillerato;
    String abanderado;
    String discapacidad;
    String carrera;

    /**
     * Creates new form Meritos
     */
    public Meritos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        nombre_postu = new javax.swing.JTextField();
        mensaje_01 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        si_abanderado = new javax.swing.JCheckBox();
        no_discapacidad = new javax.swing.JCheckBox();
        mensaje_2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        no_abanderado = new javax.swing.JCheckBox();
        si_discapacidad = new javax.swing.JCheckBox();
        mensaje_3 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        mensaje_4 = new javax.swing.JLabel();
        administracion_empresas = new javax.swing.JCheckBox();
        medicina = new javax.swing.JCheckBox();
        fisioterapia1 = new javax.swing.JCheckBox();
        dietetica = new javax.swing.JCheckBox();
        mensaje_5 = new javax.swing.JLabel();
        enfermeria1 = new javax.swing.JCheckBox();
        economia = new javax.swing.JCheckBox();
        contabilidad_auditoria = new javax.swing.JCheckBox();
        finanzas = new javax.swing.JCheckBox();
        agropecuaria = new javax.swing.JCheckBox();
        mensaje_6 = new javax.swing.JLabel();
        gastronomia = new javax.swing.JCheckBox();
        alimentos = new javax.swing.JCheckBox();
        biologia = new javax.swing.JCheckBox();
        ambiental = new javax.swing.JCheckBox();
        industrial = new javax.swing.JCheckBox();
        quimica = new javax.swing.JCheckBox();
        bio_farmacia = new javax.swing.JCheckBox();
        mensaje_7 = new javax.swing.JLabel();
        escenicas = new javax.swing.JCheckBox();
        visulaes = new javax.swing.JCheckBox();
        idiomas = new javax.swing.JCheckBox();
        psicologia = new javax.swing.JCheckBox();
        psicopedadogia = new javax.swing.JCheckBox();
        psico_clinica = new javax.swing.JCheckBox();
        mensaje_8 = new javax.swing.JLabel();
        derecho = new javax.swing.JCheckBox();
        mensaje_9 = new javax.swing.JLabel();
        geologia = new javax.swing.JCheckBox();
        telecomunicaciones = new javax.swing.JCheckBox();
        arquitectura = new javax.swing.JCheckBox();
        civil = new javax.swing.JCheckBox();
        computacion = new javax.swing.JCheckBox();
        mensaje_10 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        b_t = new javax.swing.JCheckBox();
        b_i = new javax.swing.JCheckBox();
        b_c_a = new javax.swing.JCheckBox();
        b_g_u = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 66, 112));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/LOGO MEJORADO.png"))); // NOI18N

        jLabel2.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("DECIDE SER MÁS");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1051, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(19, 19, 19))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 70));

        jPanel4.setBackground(new java.awt.Color(0, 66, 112));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1370, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 650, 1370, 50));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        nombre_postu.setForeground(new java.awt.Color(153, 153, 153));
        nombre_postu.setText("Ingrese su nombre y su apellido");
        nombre_postu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nombre_postuMousePressed(evt);
            }
        });

        mensaje_01.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 14)); // NOI18N
        mensaje_01.setText("ES USTED ABANDERADO DE SU COLEGIO?");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        si_abanderado.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 18)); // NOI18N
        si_abanderado.setText("SI");
        si_abanderado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                si_abanderadoActionPerformed(evt);
            }
        });

        no_discapacidad.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 18)); // NOI18N
        no_discapacidad.setText("NO");
        no_discapacidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no_discapacidadActionPerformed(evt);
            }
        });

        mensaje_2.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 14)); // NOI18N
        mensaje_2.setText("USTED POSEE UNA DISCAPACIDAD MAYOR AL 35%?");

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        no_abanderado.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 18)); // NOI18N
        no_abanderado.setText("NO");
        no_abanderado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no_abanderadoActionPerformed(evt);
            }
        });

        si_discapacidad.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 18)); // NOI18N
        si_discapacidad.setText("SI");
        si_discapacidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                si_discapacidadActionPerformed(evt);
            }
        });

        mensaje_3.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 14)); // NOI18N
        mensaje_3.setText("QUE CARRERA DESA ESCOJER?");

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        mensaje_4.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 14)); // NOI18N
        mensaje_4.setText("CIENCIAS DE LA SALUD");

        administracion_empresas.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        administracion_empresas.setText("Administración de empresas");
        administracion_empresas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                administracion_empresasActionPerformed(evt);
            }
        });

        medicina.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        medicina.setText("Medicina");
        medicina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                medicinaActionPerformed(evt);
            }
        });

        fisioterapia1.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        fisioterapia1.setText("Fisoterapia");
        fisioterapia1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fisioterapia1ActionPerformed(evt);
            }
        });

        dietetica.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        dietetica.setText("Nutrición y dietética");
        dietetica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dieteticaActionPerformed(evt);
            }
        });

        mensaje_5.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 14)); // NOI18N
        mensaje_5.setText("CIENCIAS ECONOMICAS Y EMPRESARIALES");

        enfermeria1.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        enfermeria1.setText("Enfermería");
        enfermeria1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enfermeria1ActionPerformed(evt);
            }
        });

        economia.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        economia.setText("Economía");
        economia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                economiaActionPerformed(evt);
            }
        });

        contabilidad_auditoria.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        contabilidad_auditoria.setText("Contabilidad y auditoría");
        contabilidad_auditoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contabilidad_auditoriaActionPerformed(evt);
            }
        });

        finanzas.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        finanzas.setText("Finanzas");
        finanzas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finanzasActionPerformed(evt);
            }
        });

        agropecuaria.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        agropecuaria.setText("Agropecuaria");
        agropecuaria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agropecuariaActionPerformed(evt);
            }
        });

        mensaje_6.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 14)); // NOI18N
        mensaje_6.setText("CIENCIAS EXACTAS Y NATURALES");

        gastronomia.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        gastronomia.setText("Gastronomía");
        gastronomia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gastronomiaActionPerformed(evt);
            }
        });

        alimentos.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        alimentos.setText("Alimentos");
        alimentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alimentosActionPerformed(evt);
            }
        });

        biologia.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        biologia.setText("Biología");
        biologia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                biologiaActionPerformed(evt);
            }
        });

        ambiental.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        ambiental.setText("Ingeniería ambiental");
        ambiental.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ambientalActionPerformed(evt);
            }
        });

        industrial.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        industrial.setText("Ingeniería industrial");
        industrial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                industrialActionPerformed(evt);
            }
        });

        quimica.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        quimica.setText("Ingeniería química");
        quimica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quimicaActionPerformed(evt);
            }
        });

        bio_farmacia.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        bio_farmacia.setText("Bioquímica y farmacia");
        bio_farmacia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bio_farmaciaActionPerformed(evt);
            }
        });

        mensaje_7.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 14)); // NOI18N
        mensaje_7.setText("CIENCIAS SOCIALES, EDUCACION Y HUMANIDADES");

        escenicas.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        escenicas.setText("Artes escénicas");
        escenicas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                escenicasActionPerformed(evt);
            }
        });

        visulaes.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        visulaes.setText("Artes visuales");
        visulaes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                visulaesActionPerformed(evt);
            }
        });

        idiomas.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        idiomas.setText("Pedagogía de los idiomas nacionales y extranjeros");
        idiomas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idiomasActionPerformed(evt);
            }
        });

        psicologia.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        psicologia.setText("Psicología");
        psicologia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psicologiaActionPerformed(evt);
            }
        });

        psicopedadogia.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        psicopedadogia.setText("Psicopedagogía");
        psicopedadogia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psicopedadogiaActionPerformed(evt);
            }
        });

        psico_clinica.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        psico_clinica.setText("Psicología clínica");
        psico_clinica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                psico_clinicaActionPerformed(evt);
            }
        });

        mensaje_8.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 14)); // NOI18N
        mensaje_8.setText("CIENCIAS JURIDICAS Y POLITICAS");

        derecho.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        derecho.setText("Derecho");
        derecho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                derechoActionPerformed(evt);
            }
        });

        mensaje_9.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 14)); // NOI18N
        mensaje_9.setText("Ingienierias y arquitecturas");

        geologia.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        geologia.setText("Geología");
        geologia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geologiaActionPerformed(evt);
            }
        });

        telecomunicaciones.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        telecomunicaciones.setText("Telecomunicaciones");
        telecomunicaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telecomunicacionesActionPerformed(evt);
            }
        });

        arquitectura.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        arquitectura.setText("Arquitectura");
        arquitectura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arquitecturaActionPerformed(evt);
            }
        });

        civil.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        civil.setText("Ingeniería civil");
        civil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                civilActionPerformed(evt);
            }
        });

        computacion.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        computacion.setText("Computación");
        computacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                computacionActionPerformed(evt);
            }
        });

        mensaje_10.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 14)); // NOI18N
        mensaje_10.setText("QUÉ TIPO DE BACHILLERATO CUENTA?");

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));

        b_t.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        b_t.setText("B.T");
        b_t.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_tActionPerformed(evt);
            }
        });

        b_i.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        b_i.setText("B.I");
        b_i.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_iActionPerformed(evt);
            }
        });

        b_c_a.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        b_c_a.setText("B.C.A");
        b_c_a.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_c_aActionPerformed(evt);
            }
        });

        b_g_u.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        b_g_u.setText("B.G.U");
        b_g_u.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_g_uActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(0, 66, 112));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PROCESO DE INSCRIPCION");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(9, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(0, 66, 112));

        jLabel4.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("INSICRIBIRSE");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel4MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(mensaje_01, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(mensaje_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(mensaje_3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(si_discapacidad)
                                    .addComponent(no_discapacidad)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(53, 53, 53)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(no_abanderado)
                                    .addComponent(si_abanderado)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(medicina)
                                    .addComponent(fisioterapia1)
                                    .addComponent(dietetica)
                                    .addComponent(enfermeria1)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(economia)
                                            .addComponent(administracion_empresas)
                                            .addComponent(contabilidad_auditoria)
                                            .addComponent(finanzas)
                                            .addComponent(agropecuaria)
                                            .addComponent(gastronomia)
                                            .addComponent(alimentos)
                                            .addComponent(biologia)
                                            .addComponent(ambiental)
                                            .addComponent(industrial)
                                            .addComponent(bio_farmacia)
                                            .addComponent(quimica)
                                            .addComponent(escenicas)
                                            .addComponent(visulaes)
                                            .addComponent(idiomas)
                                            .addComponent(psicologia)
                                            .addComponent(psicopedadogia)
                                            .addComponent(psico_clinica)
                                            .addComponent(derecho)
                                            .addComponent(computacion)
                                            .addComponent(geologia)
                                            .addComponent(telecomunicaciones)
                                            .addComponent(arquitectura)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(civil, javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                                        .addGap(21, 21, 21)
                                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(mensaje_7)
                                                            .addComponent(mensaje_6)
                                                            .addComponent(mensaje_8)
                                                            .addComponent(mensaje_9))))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addComponent(mensaje_5))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(mensaje_4)))
                                .addGap(32, 32, 32))
                            .addComponent(nombre_postu, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(mensaje_10, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(b_t)
                            .addComponent(b_i)
                            .addComponent(b_c_a)
                            .addComponent(b_g_u)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(295, 295, 295))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(nombre_postu, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(mensaje_10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b_g_u)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b_i)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b_t)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b_c_a)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mensaje_01)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(si_abanderado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(no_abanderado)
                .addGap(18, 18, 18)
                .addComponent(mensaje_2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(si_discapacidad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(no_discapacidad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mensaje_3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(mensaje_4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enfermeria1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fisioterapia1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(medicina)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dietetica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mensaje_5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(administracion_empresas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contabilidad_auditoria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(economia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(finanzas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gastronomia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mensaje_6)
                .addGap(12, 12, 12)
                .addComponent(agropecuaria)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(alimentos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(biologia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ambiental)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(industrial)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(quimica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bio_farmacia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mensaje_7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(escenicas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(visulaes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(idiomas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(psicologia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(psicopedadogia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(psico_clinica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(mensaje_8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(derecho)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mensaje_9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(computacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(geologia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(telecomunicaciones)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(arquitectura)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(civil)
                .addGap(27, 27, 27)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel2);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 870, 580));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_g_uActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_g_uActionPerformed
        Procesar_opciones manejarcheckbox = new Procesar_opciones(b_g_u, b_i, b_t, b_c_a);
        b_g_u.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                manejarcheckbox.preparar_opciones(b_g_u);
            }
        });

        manejarcheckbox.preparar_opciones(b_g_u);
        bachillerato = b_g_u.getText();
        System.out.println(bachillerato);
    }//GEN-LAST:event_b_g_uActionPerformed

    private void b_iActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_iActionPerformed
        Procesar_opciones manejarcheckbox = new Procesar_opciones(b_g_u, b_i, b_t, b_c_a);
        b_i.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                manejarcheckbox.preparar_opciones(b_i);
            }
        });
        manejarcheckbox.preparar_opciones(b_i);
        bachillerato = b_i.getText();
        System.out.println(bachillerato);
    }//GEN-LAST:event_b_iActionPerformed

    private void b_tActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_tActionPerformed
        Procesar_opciones manejarcheckbox = new Procesar_opciones(b_g_u, b_i, b_t, b_c_a);
        b_t.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                manejarcheckbox.preparar_opciones(b_t);
            }
        });
        manejarcheckbox.preparar_opciones(b_t);
        bachillerato = b_t.getText();
        System.out.println(bachillerato);
    }//GEN-LAST:event_b_tActionPerformed

    private void b_c_aActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_c_aActionPerformed
        Procesar_opciones manejarcheckbox = new Procesar_opciones(b_g_u, b_i, b_t, b_c_a);
        b_c_a.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                manejarcheckbox.preparar_opciones(b_c_a);
            }
        });
        manejarcheckbox.preparar_opciones(b_c_a);
        bachillerato = b_c_a.getText();
        System.out.println(bachillerato);
    }//GEN-LAST:event_b_c_aActionPerformed

    private void si_abanderadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_si_abanderadoActionPerformed
        Procesar_opciones manejarcheckbox = new Procesar_opciones(si_abanderado, no_abanderado);
        si_abanderado.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                manejarcheckbox.preparar_opciones(si_abanderado);
            }
        });
        manejarcheckbox.preparar_opciones(si_abanderado);
        this.abanderado = si_abanderado.getText();
        System.out.println(abanderado);
    }//GEN-LAST:event_si_abanderadoActionPerformed

    private void no_abanderadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no_abanderadoActionPerformed
        Procesar_opciones manejarcheckbox = new Procesar_opciones(si_abanderado, no_abanderado);
        no_abanderado.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                manejarcheckbox.preparar_opciones(no_abanderado);
            }
        });
        manejarcheckbox.preparar_opciones(no_abanderado);
        this.abanderado = no_abanderado.getText();
        System.out.println(abanderado);
    }//GEN-LAST:event_no_abanderadoActionPerformed

    private void si_discapacidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_si_discapacidadActionPerformed
        Procesar_opciones manejarcheckbox = new Procesar_opciones(si_discapacidad, no_discapacidad);
        si_discapacidad.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                manejarcheckbox.preparar_opciones(si_discapacidad);
            }
        });
        manejarcheckbox.preparar_opciones(si_discapacidad);
        this.discapacidad = si_discapacidad.getText();
        System.out.println(discapacidad);
    }//GEN-LAST:event_si_discapacidadActionPerformed

    private void no_discapacidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no_discapacidadActionPerformed
        Procesar_opciones manejarcheckbox = new Procesar_opciones(si_discapacidad, no_discapacidad);
        no_discapacidad.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                manejarcheckbox.preparar_opciones(no_discapacidad);
            }
        });
        manejarcheckbox.preparar_opciones(no_discapacidad);
        this.discapacidad = no_discapacidad.getText();
        System.out.println(discapacidad);
    }//GEN-LAST:event_no_discapacidadActionPerformed

    private void enfermeria1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enfermeria1ActionPerformed
        Procesar_opciones manejarcheckbox = new Procesar_opciones(dietetica, enfermeria1, fisioterapia1, dietetica, administracion_empresas, contabilidad_auditoria, economia, finanzas, gastronomia, alimentos, biologia, ambiental, industrial, quimica, bio_farmacia, agropecuaria, escenicas, visulaes, idiomas, psicologia, psicopedadogia, psico_clinica, derecho, computacion, geologia, telecomunicaciones, arquitectura, civil);
        enfermeria1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                manejarcheckbox.preparar_opciones(enfermeria1);
            }
        });
        manejarcheckbox.preparar_opciones(enfermeria1);
        this.carrera = enfermeria1.getText();
        System.out.println(carrera);
    }//GEN-LAST:event_enfermeria1ActionPerformed

    private void fisioterapia1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fisioterapia1ActionPerformed
        Procesar_opciones manejarcheckbox = new Procesar_opciones(dietetica, enfermeria1, fisioterapia1, dietetica, administracion_empresas, contabilidad_auditoria, economia, finanzas, gastronomia, alimentos, biologia, ambiental, industrial, quimica, bio_farmacia, agropecuaria, escenicas, visulaes, idiomas, psicologia, psicopedadogia, psico_clinica, derecho, computacion, geologia, telecomunicaciones, arquitectura, civil);

        fisioterapia1.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                manejarcheckbox.preparar_opciones(fisioterapia1);
            }
        });
        manejarcheckbox.preparar_opciones(fisioterapia1);
        this.carrera = fisioterapia1.getText();
        System.out.println(carrera);
    }//GEN-LAST:event_fisioterapia1ActionPerformed

    private void medicinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_medicinaActionPerformed
        Procesar_opciones manejarcheckbox = new Procesar_opciones(dietetica, enfermeria1, fisioterapia1, dietetica, administracion_empresas, contabilidad_auditoria, economia, finanzas, gastronomia, alimentos, biologia, ambiental, industrial, quimica, bio_farmacia, agropecuaria, escenicas, visulaes, idiomas, psicologia, psicopedadogia, psico_clinica, derecho, computacion, geologia, telecomunicaciones, arquitectura, civil);
        medicina.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                manejarcheckbox.preparar_opciones(medicina);
            }
        });
        manejarcheckbox.preparar_opciones(medicina);
        this.carrera = medicina.getText();
        System.out.println(carrera);
    }//GEN-LAST:event_medicinaActionPerformed

    private void dieteticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dieteticaActionPerformed
        Procesar_opciones manejarcheckbox = new Procesar_opciones(dietetica, enfermeria1, fisioterapia1, dietetica, administracion_empresas, contabilidad_auditoria, economia, finanzas, gastronomia, alimentos, biologia, ambiental, industrial, quimica, bio_farmacia, agropecuaria, escenicas, visulaes, idiomas, psicologia, psicopedadogia, psico_clinica, derecho, computacion, geologia, telecomunicaciones, arquitectura, civil);
        dietetica.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                manejarcheckbox.preparar_opciones(dietetica);
            }
        });
        manejarcheckbox.preparar_opciones(dietetica);
        this.carrera = dietetica.getText();
        System.out.println(carrera);
    }//GEN-LAST:event_dieteticaActionPerformed

    private void administracion_empresasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_administracion_empresasActionPerformed
        Procesar_opciones manejarcheckbox = new Procesar_opciones(dietetica, enfermeria1, fisioterapia1, dietetica, administracion_empresas, contabilidad_auditoria, economia, finanzas, gastronomia, alimentos, biologia, ambiental, industrial, quimica, bio_farmacia, agropecuaria, escenicas, visulaes, idiomas, psicologia, psicopedadogia, psico_clinica, derecho, computacion, geologia, telecomunicaciones, arquitectura, civil);
        administracion_empresas.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                manejarcheckbox.preparar_opciones(administracion_empresas);
            }
        });
        manejarcheckbox.preparar_opciones(administracion_empresas);
        this.carrera = administracion_empresas.getText();
        System.out.println(carrera);

    }//GEN-LAST:event_administracion_empresasActionPerformed

    private void contabilidad_auditoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contabilidad_auditoriaActionPerformed
        Procesar_opciones manejarcheckbox = new Procesar_opciones(dietetica, enfermeria1, fisioterapia1, dietetica, administracion_empresas, contabilidad_auditoria, economia, finanzas, gastronomia, alimentos, biologia, ambiental, industrial, quimica, bio_farmacia, agropecuaria, escenicas, visulaes, idiomas, psicologia, psicopedadogia, psico_clinica, derecho, computacion, geologia, telecomunicaciones, arquitectura, civil);
        contabilidad_auditoria.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                manejarcheckbox.preparar_opciones(contabilidad_auditoria);
            }
        });
        manejarcheckbox.preparar_opciones(contabilidad_auditoria);
        this.carrera = contabilidad_auditoria.getText();
        System.out.println(carrera);
    }//GEN-LAST:event_contabilidad_auditoriaActionPerformed

    private void economiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_economiaActionPerformed
        Procesar_opciones manejarcheckbox = new Procesar_opciones(dietetica, enfermeria1, fisioterapia1, dietetica, administracion_empresas, contabilidad_auditoria, economia, finanzas, gastronomia, alimentos, biologia, ambiental, industrial, quimica, bio_farmacia, agropecuaria, escenicas, visulaes, idiomas, psicologia, psicopedadogia, psico_clinica, derecho, computacion, geologia, telecomunicaciones, arquitectura, civil);
        economia.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                manejarcheckbox.preparar_opciones(economia);
            }
        });
        manejarcheckbox.preparar_opciones(economia);
        this.carrera = economia.getText();
        System.out.println(carrera);
    }//GEN-LAST:event_economiaActionPerformed

    private void finanzasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finanzasActionPerformed
        Procesar_opciones manejarcheckbox = new Procesar_opciones(dietetica, enfermeria1, fisioterapia1, dietetica, administracion_empresas, contabilidad_auditoria, economia, finanzas, gastronomia, alimentos, biologia, ambiental, industrial, quimica, bio_farmacia, agropecuaria, escenicas, visulaes, idiomas, psicologia, psicopedadogia, psico_clinica, derecho, computacion, geologia, telecomunicaciones, arquitectura, civil);
        finanzas.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                manejarcheckbox.preparar_opciones(finanzas);
            }
        });
        manejarcheckbox.preparar_opciones(finanzas);
        this.carrera = finanzas.getText();
        System.out.println(carrera);
    }//GEN-LAST:event_finanzasActionPerformed

    private void gastronomiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gastronomiaActionPerformed
        Procesar_opciones manejarcheckbox = new Procesar_opciones(dietetica, enfermeria1, fisioterapia1, dietetica, administracion_empresas, contabilidad_auditoria, economia, finanzas, gastronomia, alimentos, biologia, ambiental, industrial, quimica, bio_farmacia, agropecuaria, escenicas, visulaes, idiomas, psicologia, psicopedadogia, psico_clinica, derecho, computacion, geologia, telecomunicaciones, arquitectura, civil);
        gastronomia.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                manejarcheckbox.preparar_opciones(gastronomia);
            }
        });
        manejarcheckbox.preparar_opciones(gastronomia);
        this.carrera = gastronomia.getText();
        System.out.println(carrera);
    }//GEN-LAST:event_gastronomiaActionPerformed

    private void agropecuariaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agropecuariaActionPerformed
        Procesar_opciones manejarcheckbox = new Procesar_opciones(dietetica, enfermeria1, fisioterapia1, dietetica, administracion_empresas, contabilidad_auditoria, economia, finanzas, gastronomia, alimentos, biologia, ambiental, industrial, quimica, bio_farmacia, agropecuaria, escenicas, visulaes, idiomas, psicologia, psicopedadogia, psico_clinica, derecho, computacion, geologia, telecomunicaciones, arquitectura, civil);
        agropecuaria.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                manejarcheckbox.preparar_opciones(agropecuaria);
            }
        });
        manejarcheckbox.preparar_opciones(agropecuaria);
        this.carrera = agropecuaria.getText();
        System.out.println(carrera);
    }//GEN-LAST:event_agropecuariaActionPerformed

    private void alimentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alimentosActionPerformed
        Procesar_opciones manejarcheckbox = new Procesar_opciones(dietetica, enfermeria1, fisioterapia1, dietetica, administracion_empresas, contabilidad_auditoria, economia, finanzas, gastronomia, alimentos, biologia, ambiental, industrial, quimica, bio_farmacia, agropecuaria, escenicas, visulaes, idiomas, psicologia, psicopedadogia, psico_clinica, derecho, computacion, geologia, telecomunicaciones, arquitectura, civil);
        alimentos.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                manejarcheckbox.preparar_opciones(alimentos);
            }
        });
        manejarcheckbox.preparar_opciones(alimentos);
        this.carrera = alimentos.getText();
        System.out.println(carrera);
    }//GEN-LAST:event_alimentosActionPerformed

    private void biologiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_biologiaActionPerformed
        Procesar_opciones manejarcheckbox = new Procesar_opciones(dietetica, enfermeria1, fisioterapia1, dietetica, administracion_empresas, contabilidad_auditoria, economia, finanzas, gastronomia, alimentos, biologia, ambiental, industrial, quimica, bio_farmacia, agropecuaria, escenicas, visulaes, idiomas, psicologia, psicopedadogia, psico_clinica, derecho, computacion, geologia, telecomunicaciones, arquitectura, civil);
        biologia.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                manejarcheckbox.preparar_opciones(biologia);
            }
        });
        manejarcheckbox.preparar_opciones(biologia);
        this.carrera = biologia.getText();
        System.out.println(carrera);
    }//GEN-LAST:event_biologiaActionPerformed

    private void ambientalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ambientalActionPerformed
        Procesar_opciones manejarcheckbox = new Procesar_opciones(dietetica, enfermeria1, fisioterapia1, dietetica, administracion_empresas, contabilidad_auditoria, economia, finanzas, gastronomia, alimentos, biologia, ambiental, industrial, quimica, bio_farmacia, agropecuaria, escenicas, visulaes, idiomas, psicologia, psicopedadogia, psico_clinica, derecho, computacion, geologia, telecomunicaciones, arquitectura, civil);
        ambiental.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                manejarcheckbox.preparar_opciones(ambiental);
            }
        });
        manejarcheckbox.preparar_opciones(ambiental);
        this.carrera = ambiental.getText();
        System.out.println(carrera);
    }//GEN-LAST:event_ambientalActionPerformed

    private void industrialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_industrialActionPerformed
        Procesar_opciones manejarcheckbox = new Procesar_opciones(dietetica, enfermeria1, fisioterapia1, dietetica, administracion_empresas, contabilidad_auditoria, economia, finanzas, gastronomia, alimentos, biologia, ambiental, industrial, quimica, bio_farmacia, agropecuaria, escenicas, visulaes, idiomas, psicologia, psicopedadogia, psico_clinica, derecho, computacion, geologia, telecomunicaciones, arquitectura, civil);
        industrial.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                manejarcheckbox.preparar_opciones(industrial);
            }
        });
        manejarcheckbox.preparar_opciones(industrial);
        this.carrera = industrial.getText();
        System.out.println(carrera);
    }//GEN-LAST:event_industrialActionPerformed

    private void quimicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quimicaActionPerformed
        Procesar_opciones manejarcheckbox = new Procesar_opciones(dietetica, enfermeria1, fisioterapia1, dietetica, administracion_empresas, contabilidad_auditoria, economia, finanzas, gastronomia, alimentos, biologia, ambiental, industrial, quimica, bio_farmacia, agropecuaria, escenicas, visulaes, idiomas, psicologia, psicopedadogia, psico_clinica, derecho, computacion, geologia, telecomunicaciones, arquitectura, civil);
        quimica.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                manejarcheckbox.preparar_opciones(quimica);
            }
        });
        manejarcheckbox.preparar_opciones(quimica);
        this.carrera = quimica.getText();
        System.out.println(carrera);
    }//GEN-LAST:event_quimicaActionPerformed

    private void bio_farmaciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bio_farmaciaActionPerformed
        Procesar_opciones manejarcheckbox = new Procesar_opciones(dietetica, enfermeria1, fisioterapia1, dietetica, administracion_empresas, contabilidad_auditoria, economia, finanzas, gastronomia, alimentos, biologia, ambiental, industrial, quimica, bio_farmacia, agropecuaria, escenicas, visulaes, idiomas, psicologia, psicopedadogia, psico_clinica, derecho, computacion, geologia, telecomunicaciones, arquitectura, civil);
        bio_farmacia.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                manejarcheckbox.preparar_opciones(bio_farmacia);
            }
        });
        manejarcheckbox.preparar_opciones(bio_farmacia);
        this.carrera = bio_farmacia.getText();
        System.out.println(carrera);
    }//GEN-LAST:event_bio_farmaciaActionPerformed

    private void escenicasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_escenicasActionPerformed
        Procesar_opciones manejarcheckbox = new Procesar_opciones(dietetica, enfermeria1, fisioterapia1, dietetica, administracion_empresas, contabilidad_auditoria, economia, finanzas, gastronomia, alimentos, biologia, ambiental, industrial, quimica, bio_farmacia, agropecuaria, escenicas, visulaes, idiomas, psicologia, psicopedadogia, psico_clinica, derecho, computacion, geologia, telecomunicaciones, arquitectura, civil);
        escenicas.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                manejarcheckbox.preparar_opciones(escenicas);
            }
        });
        manejarcheckbox.preparar_opciones(escenicas);
        this.carrera = escenicas.getText();
        System.out.println(carrera);
    }//GEN-LAST:event_escenicasActionPerformed

    private void visulaesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_visulaesActionPerformed
        Procesar_opciones manejarcheckbox = new Procesar_opciones(dietetica, enfermeria1, fisioterapia1, dietetica, administracion_empresas, contabilidad_auditoria, economia, finanzas, gastronomia, alimentos, biologia, ambiental, industrial, quimica, bio_farmacia, agropecuaria, escenicas, visulaes, idiomas, psicologia, psicopedadogia, psico_clinica, derecho, computacion, geologia, telecomunicaciones, arquitectura, civil);
        visulaes.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                manejarcheckbox.preparar_opciones(visulaes);
            }
        });
        manejarcheckbox.preparar_opciones(visulaes);
        this.carrera = visulaes.getText();
        System.out.println(carrera);
    }//GEN-LAST:event_visulaesActionPerformed

    private void idiomasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idiomasActionPerformed
        Procesar_opciones manejarcheckbox = new Procesar_opciones(dietetica, enfermeria1, fisioterapia1, dietetica, administracion_empresas, contabilidad_auditoria, economia, finanzas, gastronomia, alimentos, biologia, ambiental, industrial, quimica, bio_farmacia, agropecuaria, escenicas, visulaes, idiomas, psicologia, psicopedadogia, psico_clinica, derecho, computacion, geologia, telecomunicaciones, arquitectura, civil);
        idiomas.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                manejarcheckbox.preparar_opciones(idiomas);
            }
        });
        manejarcheckbox.preparar_opciones(idiomas);
        this.carrera = idiomas.getText();
        System.out.println(carrera);
    }//GEN-LAST:event_idiomasActionPerformed

    private void psicologiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_psicologiaActionPerformed
        Procesar_opciones manejarcheckbox = new Procesar_opciones(dietetica, enfermeria1, fisioterapia1, dietetica, administracion_empresas, contabilidad_auditoria, economia, finanzas, gastronomia, alimentos, biologia, ambiental, industrial, quimica, bio_farmacia, agropecuaria, escenicas, visulaes, idiomas, psicologia, psicopedadogia, psico_clinica, derecho, computacion, geologia, telecomunicaciones, arquitectura, civil);
        psicologia.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                manejarcheckbox.preparar_opciones(psicologia);
            }
        });
        manejarcheckbox.preparar_opciones(psicologia);
        this.carrera = psicologia.getText();
        System.out.println(carrera);
    }//GEN-LAST:event_psicologiaActionPerformed

    private void psicopedadogiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_psicopedadogiaActionPerformed
        Procesar_opciones manejarcheckbox = new Procesar_opciones(dietetica, enfermeria1, fisioterapia1, dietetica, administracion_empresas, contabilidad_auditoria, economia, finanzas, gastronomia, alimentos, biologia, ambiental, industrial, quimica, bio_farmacia, agropecuaria, escenicas, visulaes, idiomas, psicologia, psicopedadogia, psico_clinica, derecho, computacion, geologia, telecomunicaciones, arquitectura, civil);
        psicopedadogia.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                manejarcheckbox.preparar_opciones(psicopedadogia);
            }
        });
        manejarcheckbox.preparar_opciones(psicopedadogia);
        this.carrera = psicopedadogia.getText();
        System.out.println(carrera);
    }//GEN-LAST:event_psicopedadogiaActionPerformed

    private void psico_clinicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_psico_clinicaActionPerformed
        Procesar_opciones manejarcheckbox = new Procesar_opciones(dietetica, enfermeria1, fisioterapia1, dietetica, administracion_empresas, contabilidad_auditoria, economia, finanzas, gastronomia, alimentos, biologia, ambiental, industrial, quimica, bio_farmacia, agropecuaria, escenicas, visulaes, idiomas, psicologia, psicopedadogia, psico_clinica, derecho, computacion, geologia, telecomunicaciones, arquitectura, civil);
        psico_clinica.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                manejarcheckbox.preparar_opciones(psico_clinica);
            }
        });
        manejarcheckbox.preparar_opciones(psico_clinica);
        this.carrera = psico_clinica.getText();
        System.out.println(carrera);
    }//GEN-LAST:event_psico_clinicaActionPerformed

    private void derechoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_derechoActionPerformed
        Procesar_opciones manejarcheckbox = new Procesar_opciones(dietetica, enfermeria1, fisioterapia1, dietetica, administracion_empresas, contabilidad_auditoria, economia, finanzas, gastronomia, alimentos, biologia, ambiental, industrial, quimica, bio_farmacia, agropecuaria, escenicas, visulaes, idiomas, psicologia, psicopedadogia, psico_clinica, derecho, computacion, geologia, telecomunicaciones, arquitectura, civil);
        derecho.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                manejarcheckbox.preparar_opciones(derecho);
            }
        });
        manejarcheckbox.preparar_opciones(derecho);
        this.carrera = derecho.getText();
        System.out.println(carrera);
    }//GEN-LAST:event_derechoActionPerformed

    private void computacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_computacionActionPerformed
        Procesar_opciones manejarcheckbox = new Procesar_opciones(dietetica, enfermeria1, fisioterapia1, dietetica, administracion_empresas, contabilidad_auditoria, economia, finanzas, gastronomia, alimentos, biologia, ambiental, industrial, quimica, bio_farmacia, agropecuaria, escenicas, visulaes, idiomas, psicologia, psicopedadogia, psico_clinica, derecho, computacion, geologia, telecomunicaciones, arquitectura, civil);
        computacion.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                manejarcheckbox.preparar_opciones(computacion);
            }
        });
        manejarcheckbox.preparar_opciones(computacion);
        this.carrera = computacion.getText();
        System.out.println(carrera);
    }//GEN-LAST:event_computacionActionPerformed

    private void geologiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geologiaActionPerformed
        Procesar_opciones manejarcheckbox = new Procesar_opciones(dietetica, enfermeria1, fisioterapia1, dietetica, administracion_empresas, contabilidad_auditoria, economia, finanzas, gastronomia, alimentos, biologia, ambiental, industrial, quimica, bio_farmacia, agropecuaria, escenicas, visulaes, idiomas, psicologia, psicopedadogia, psico_clinica, derecho, computacion, geologia, telecomunicaciones, arquitectura, civil);
        geologia.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                manejarcheckbox.preparar_opciones(geologia);
            }
        });
        manejarcheckbox.preparar_opciones(geologia);
        this.carrera = geologia.getText();
        System.out.println(carrera);
    }//GEN-LAST:event_geologiaActionPerformed

    private void telecomunicacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telecomunicacionesActionPerformed
        Procesar_opciones manejarcheckbox = new Procesar_opciones(dietetica, enfermeria1, fisioterapia1, dietetica, administracion_empresas, contabilidad_auditoria, economia, finanzas, gastronomia, alimentos, biologia, ambiental, industrial, quimica, bio_farmacia, agropecuaria, escenicas, visulaes, idiomas, psicologia, psicopedadogia, psico_clinica, derecho, computacion, geologia, telecomunicaciones, arquitectura, civil);
        telecomunicaciones.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                manejarcheckbox.preparar_opciones(telecomunicaciones);
            }
        });
        manejarcheckbox.preparar_opciones(telecomunicaciones);
        this.carrera = telecomunicaciones.getText();
        System.out.println(carrera);
    }//GEN-LAST:event_telecomunicacionesActionPerformed

    private void arquitecturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arquitecturaActionPerformed
        Procesar_opciones manejarcheckbox = new Procesar_opciones(dietetica, enfermeria1, fisioterapia1, dietetica, administracion_empresas, contabilidad_auditoria, economia, finanzas, gastronomia, alimentos, biologia, ambiental, industrial, quimica, bio_farmacia, agropecuaria, escenicas, visulaes, idiomas, psicologia, psicopedadogia, psico_clinica, derecho, computacion, geologia, telecomunicaciones, arquitectura, civil);
        arquitectura.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                manejarcheckbox.preparar_opciones(arquitectura);
            }
        });
        manejarcheckbox.preparar_opciones(arquitectura);
        this.carrera = arquitectura.getText();
        System.out.println(carrera);
    }//GEN-LAST:event_arquitecturaActionPerformed

    private void civilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_civilActionPerformed
        Procesar_opciones manejarcheckbox = new Procesar_opciones(dietetica, enfermeria1, fisioterapia1, dietetica, administracion_empresas, contabilidad_auditoria, economia, finanzas, gastronomia, alimentos, biologia, ambiental, industrial, quimica, bio_farmacia, agropecuaria, escenicas, visulaes, idiomas, psicologia, psicopedadogia, psico_clinica, derecho, computacion, geologia, telecomunicaciones, arquitectura, civil);
        civil.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent evt) {
                manejarcheckbox.preparar_opciones(civil);
            }
        });
        manejarcheckbox.preparar_opciones(civil);
        this.carrera = civil.getText();
        System.out.println(carrera);
    }//GEN-LAST:event_civilActionPerformed

    private void jLabel4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MousePressed
        Requerimineto n = new Requerimineto();

        String nombre_postulante = nombre_postu.getText();
        LocalDate fechaActual = LocalDate.now();
        DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        String fecha = fechaActual.format(formato);
        boolean vf = n.verifi_fechas(fecha);
        if(vf){
        String usuario;
    String contraseña;
    
    obtener_identifi o = new obtener_identifi();
    int id = o.obtenerSiguienteNumeroDeFila(); 

    Gestion_emails gestionUsuarios = new Gestion_emails();
    usuario = gestionUsuarios.creador_usuarios(id);

    Gestion_contraseñas gestionContraseñas = new Gestion_contraseñas();
    contraseña = gestionContraseñas.creador_contraseñas();

    System.out.println(nombre_postulante);
   
    int nota = n.examen(carrera, discapacidad, bachillerato, abanderado);
    String mesj = n.mensaje(carrera, nota);
    boolean estado = n.estado(nota, carrera);
    Gestion_postulante postulante = new Gestion_postulante(nombre_postulante, fecha, bachillerato, abanderado, discapacidad, carrera, usuario, contraseña, nota, estado, mesj);
    postulante.guardar_bd();

    JOptionPane.showMessageDialog(this, "Usuario: " + usuario + "\nContraseña: " + contraseña, "Guarde la suiguiente información", JOptionPane.INFORMATION_MESSAGE);
    new Iniciar_secion().setVisible(true);
        }else{
        JOptionPane.showMessageDialog(rootPane, "se encuentra fuera del tiempo permitido, intente el proximio año");
        }


    }//GEN-LAST:event_jLabel4MousePressed

    private void nombre_postuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nombre_postuMousePressed
        if (nombre_postu.getText().equals("Ingrese su nombre y su apellido")) {
            nombre_postu.setText("");
            nombre_postu.setForeground(Color.black);
        }
    }//GEN-LAST:event_nombre_postuMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Meritos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Meritos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Meritos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Meritos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Meritos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox administracion_empresas;
    private javax.swing.JCheckBox agropecuaria;
    private javax.swing.JCheckBox alimentos;
    private javax.swing.JCheckBox ambiental;
    private javax.swing.JCheckBox arquitectura;
    private javax.swing.JCheckBox b_c_a;
    private javax.swing.JCheckBox b_g_u;
    private javax.swing.JCheckBox b_i;
    private javax.swing.JCheckBox b_t;
    private javax.swing.JCheckBox bio_farmacia;
    private javax.swing.JCheckBox biologia;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JCheckBox civil;
    private javax.swing.JCheckBox computacion;
    private javax.swing.JCheckBox contabilidad_auditoria;
    private javax.swing.JCheckBox derecho;
    private javax.swing.JCheckBox dietetica;
    private javax.swing.JCheckBox economia;
    private javax.swing.JCheckBox enfermeria1;
    private javax.swing.JCheckBox escenicas;
    private javax.swing.JCheckBox finanzas;
    private javax.swing.JCheckBox fisioterapia1;
    private javax.swing.JCheckBox gastronomia;
    private javax.swing.JCheckBox geologia;
    private javax.swing.JCheckBox idiomas;
    private javax.swing.JCheckBox industrial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JCheckBox medicina;
    private javax.swing.JLabel mensaje_01;
    private javax.swing.JLabel mensaje_10;
    private javax.swing.JLabel mensaje_2;
    private javax.swing.JLabel mensaje_3;
    private javax.swing.JLabel mensaje_4;
    private javax.swing.JLabel mensaje_5;
    private javax.swing.JLabel mensaje_6;
    private javax.swing.JLabel mensaje_7;
    private javax.swing.JLabel mensaje_8;
    private javax.swing.JLabel mensaje_9;
    private javax.swing.JCheckBox no_abanderado;
    private javax.swing.JCheckBox no_discapacidad;
    private javax.swing.JTextField nombre_postu;
    private javax.swing.JCheckBox psico_clinica;
    private javax.swing.JCheckBox psicologia;
    private javax.swing.JCheckBox psicopedadogia;
    private javax.swing.JCheckBox quimica;
    private javax.swing.JCheckBox si_abanderado;
    private javax.swing.JCheckBox si_discapacidad;
    private javax.swing.JCheckBox telecomunicaciones;
    private javax.swing.JCheckBox visulaes;
    // End of variables declaration//GEN-END:variables
}
